# Generated by Django 3.2.8 on 2022-06-16 19:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_number_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(help_text='Enter 11 digits phone number', max_length=11, unique=True, verbose_name='phonenumber'),
        ),
    ]
