# Generated by Django 3.2.8 on 2022-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
