# Generated by Django 3.2.8 on 2022-06-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_alter_code_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='time1',
            field=models.IntegerField(default=0),
        ),
    ]
