# Generated by Django 3.2.8 on 2022-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_code_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='time2',
            field=models.IntegerField(default=0),
        ),
    ]
